import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import { NavBar } from "@/components/layout/nav-tabs";
import { ThemeProvider } from "@/components/app/context/theme-provider";
import { Footer } from "@/components/layout/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <div className="overflow-hidden dark:bg-[#030014]/60">
            <NavBar />
            <main className="dark z-10 w-full dark:text-white">{children}</main>
            <Footer />
          </div>
          <Toaster richColors position="bottom-right" />{" "}
        </ThemeProvider>
      </body>
    </html>
  );
}
